
@startuml
class User{
  +id: String
  +name: String
  +surname1: String
  +surname2: String
  +email: String

}

class Customer{
  +points
  +balance
}

class Worker{
}

class Booking{
  +date
}


class Amount{
  +quantity
}

class Screen{
  +number
}

class Schedule{
  +freeHour
  +openingTime
  +closingTIme
}

class Film{
  +name
  +duration
  +description
}

class Rating{
  +mark
  +opinion
}

class Seat{
  +id
}


enum Genre{
  +Action
  +Adventure
  +Animated
  +Comedy
  +Drama
  +Fantasy
  +Historical
  +Horror
  +Musical
  +Romance
  +Science Fiction
  +Thriller
  +Western
}

enum BookingStatus{
  +Reserved
  +Completed
  +Cancelled
}

enum Food{
  +SmallPopCorn
  +MediumPopCorn
  +LargePopCorn
  +SmallSoda
  +MediumSoda
  +LargeSoda
  +Nachos
  +Candy
}

enum SeatType{
  +Normal
  +Comfortable
  +Premium
}


User <|-- Customer
User <|-- Worker


Screen "*" -- "*" Film: displays >
Screen "1" -- "*" Schedule: every day has a different >
Screen "1" -- "*" Seat: contains >

Seat "*" -- "1" SeatType

Film "1" -- "*" Rating: has
Film "*" -- "*" Genre : categorized by >


Booking "*" -- "1" Film: associated with >
Booking "*" -- "1" BookingStatus : has >
Booking "*" -- "1" Screen
Booking "1" -- "*" Seat
Booking "*" -- "*" Food: has >
(Booking, Food) .. Amount
(Booking, Seat) .. Amount



@enduml
