@startuml
skinparam actorStyle awesome
left to right direction

' Define all actors
actor User as U
actor Customer
actor Worker
actor Admin

' Move "User" behind other actors
U -[hidden]-> Customer
U -[hidden]-> Worker
U -[hidden]-> Admin

' Define generalizations
Customer --|> U
Worker --|> U
Admin --|> Worker

rectangle "Cinema Reservation Manager" {
    (Register) as UC1
    (Login) as UC2
    (Browse Movies) as UC3
    (Purchase Ticket Online) as UC4
    (Order Snacks) as UC5
    (Request Cancel Ticket) as UC6
    (Provide Reviews) as UC7
    (See Client Reservations) as UC8
    (Manage Movies and Show Times) as UC9
    (Manage Projection Rooms) as UC10
   ' (Generate Revenue Report) as UC
    (Hire Worker) as UC11
    (Fire Worker) as UC12
    (Sell Ticket in Person) as UC13
    (Accept Ticket Cancelation) as UC14

    ' User interactions
    U --> UC1
    U --> UC2

    ' Customer interactions
    Customer --> UC3
    Customer --> UC4
    Customer --> UC6
    Customer --> UC7

    ' Worker interactions
    Worker --> UC8
    Worker --> UC13
    Worker --> UC14

    ' Extend relationship for ordering snacks
    UC4 ..> UC5 : <<extends>>
    note on link
       Customer has the option to order snacks
    end note

    ' Admin interactions
    Admin --> UC9
    Admin --> UC10
    Admin --> UC12
    Admin --> UC11
}
@enduml
