@startuml
skinparam actorStyle awesome
left to right direction

actor User
actor Customer
actor Worker
actor Admin

Customer --|> User
Worker --|> User
Admin --|> User

rectangle "Cinema Reservation Manager" {
    (Register) as UC1
    (Login) as UC2
    (Browse Movies) as UC3
    (Purchase Ticket) as UC4
    (Order Snacks) as UC5
    (Cancel Ticket) as UC6
    (Provide Reviews) as UC7
    (See Client Reservations) as UC8
    (Manage Movies and Showtimes) as UC10
    (Manage Projection Rooms) as UC11
    (Generate Revenue Report) as UC12
    (Track Food Inventory) as UC13


    User --> UC1
    User --> UC2
    Customer --> UC3
    Customer --> UC4
    Customer --> UC6
    UC4 .> UC5 : <<extends>>  ' Only Customer can extend the action of ordering snacks
    Customer --> UC7

    Worker --> UC4
    Worker --> UC6
    Worker --> UC8

    Admin --> UC10
    Admin --> UC11
    Admin --> UC12
    Admin --> UC13
}

@enduml